name: LoginAuth
main: LoginAuth\Main
version: "1.0"
api: [2.0.0]
load: STARTUP
author: Jhelom
description: ログイン認証
website: https://github.com/jhelom/PocketMine-Plugin-LoginAuth

commands:
  register:
    description: "アカウント登録(LoginAuth)"
    usage: "/register <password>"
  login:
    description: "ログイン(LoginAuth)"
    usage: "/login <password>"
  auth:
    description: "アカウント管理(LoginAuth)"
    usage: "/auth < password | unregister >"

