name: LoginAuth
main: Jhelom\LoginAuth\Main
version: "1.0"
api: [2.0.0]
load: STARTUP
author: Jhelom & Dragon7
description: ログイン認証
website: https://github.com/jhelom/PocketMine-Plugin-LoginAuth

commands:
  login:
    description: "ログイン(LoginAuth)"
    usage: "/login <password>"
  register:
    description: "アカウント登録(LoginAuth)"
    usage: "/register <password>"
  password:
    description: "パスワード変更(LoginAuth)"
    usage: "/password <new-password>"
  auth:
    description: "アカウント管理(LoginAuth)"
    usage: "/auth <add|find|unregister>"


